#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""This package contains all the commands for the personal voice assistant"""

__author__ = "Justin Furuness"
__credits__ = ["Justin Furuness"]
__Lisence__ = "BSD"
__maintainer__ = "Justin Furuness"
__email__ = "jfuruness@gmail.com"
__status__ = "Development"

from .command import Command, Link_Command, Number_Command

commands = [
Link_Command(["ice", "whim", "wim", "wim hof", "whim hof", "ice man"],
             func_name="go_to_ice_man",
             name="Ice Man/Wim Hof"),
Link_Command(["meet", "event", "events", "meeting", "meetings", "zoom",
              "zoom links", "event links", "meeting links"],
             func_name="go_to_zoom",
             name="Zoom links"),
Link_Command(["husky", "blackboard", "black", "classes", "school"],
             func_name="go_to_blackboard",
             name="Huskyct"),
Link_Command(["software", "software engineering",
              "software class", "software engineering class"],
             func_name="go_to_software_engineering",
             name="CSE2102: Software Engineering"),
Link_Command(["cyber",
              "security",
              "cyber security",
              "cybersecurity",
              "cyber class",
              "security class",
              "cyber security class",
              "cyber security class",
              "cybersecurity class"],
             func_name="go_to_cyber_security",
             name="Cybersecurity"),
Link_Command(["philosophy",
              "ethics",
              "philosophy class",
              "ethics class"],
             func_name="go_to_ethics",
             name="CSE300: Ethics"),
Link_Command(["history", "history class"],
             func_name="go_to_history",
             name="HIST1502: History"),
Link_Command(["education", "education class",
              "teaching", "teaching class"],
             func_name="go_to_education",
             name=("EPSY3010: "
                   "Educational Psychology")),
Link_Command(["math", "math class"],
             func_name="go_to_math",
             name="MATH2210Q: Linear Algebra"),
Link_Command(["linear", "linear algebra", "algebra",
              "linear class", "linear algebra class",
              "algebra class"],
             func_name="go_to_math_website",
             name="Math website"),
Command(["show numbers",
         "numbers",
         "show links",
         "links"],
        func_name="show_numbers",
        _help="Displays numbers on browser"),
Command(["close"],
        func_name="close",
        _help="Close all browsers"),
Command(["off", "stop", "go to sleep", "stop listening", "die"],
        func_name="end",
        _help="Closes all browsers and ends session"),
Command(["show commands", "show help", "show hope", "help", "commands",
         "list commands", "list help", "display commands", "display help"],
        func_name="help",
        _help="Displays all commands"),
Command(["show websites", "websites", "display websites"],
        func_name="show_websites",
        _help="Show website commands"),
Directional_Command(["left"], func_name="focus_left"),
Directional_Command(["right"], func_name="focus_right"),
Directional_Command(["center", "middle", "censor"], func_name="focus_center"),
Command(["scroll down", "move down", "down"],
        func_name="scroll_down",
        _help="Scroll down"),
Command(["scroll up", "move up", "up"],
        func_name="scroll_up",
        _help="Scroll up"),
Command(["page down"],
        func_name="page_down",
        _help="Scroll down"),
Command(["page up"],
        func_name="page_up",
        _help="Scroll up"),
Command(["back", "go back"],
        func_name="back",
        _help="Go back a page"),
Command(["accept", "except", "okay", "accept pop", "accept pop up",
         "accept pop up window"],
        func_name="accept_pop_up",
        _help="Accepts pop up window"),
Command(["maximize", "maximus", "max", "enlarge"],
        func_name="maximize"),

###########################
### Unfinished commands ###
###########################

Mode_Command(["safe"], func_name="start_safe_mode", name="safe"),
Mode_Command(["google", "hey google", "search"],
             func_name="start_google_mode",
             name="google"),
Command(["download", "download html", "download as html"],
        func_name="download_as_html",
        _help="Download huskyct pop ups as html"),
Command(["move over", "shift tab", "move tab", "move tabs"],
         func_name="tab_over",
         _help="Moves tabs"),
Command(["new tab", "open new tab", "open a new tab",
         "pop open new tab", "pop open a new tab",
         "open tab"],
         func_name="new_tab",
         _help="Opens a new tab"),
Command(["unfinished", "list unfinished", "show unfinished",
         "display unfinished", "show incomplete", "incomplete",
         "display incomplete"],
         func_name="show_unfinished_functions"),
]
